typography_spectrum: 0.14016304886899889
color:
  brandStrength: 0.1895727845840156
  lightness: 0.8042250883299857
  saturation: 0.03917393949814141
  rhythmicContrast: 0.44393998966552317
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
layout_spectrum: 0.9065458569675684
name: K E Nielsen
navigation:
  - name: Blog
    url: 'http://kenielsenauthor.blogspot.com/'
    type: external
  - name: Facebook
    url: 'http://www.facebook.com/kaylaenielsen'
    type: external
title: Welcome to the Website of K E Nielsen
description: Imagination Roars
